Repository didi/Hummer, pull requests merged in 2021-08, with the labels that each got.

#261 fix(Android): napi_get_cb_info memory overlap
  android/hummer-core/src/main/jni/napi/hummer/JSEngine.cpp
Labels: bug, Platform: Android

#258 【iOS】Avoid create `HMJSCStrongValue` repeatedly
  iOS/Hummer/Classes/Core/Bridge/NSObject+Hummer.m
Labels: enhancement, Platform: iOS

#266 feat(iOS): border box implementation
  Hummer.podspec
  iOS/App.xcodeproj/project.pbxproj
  iOS/App/AppDelegate.swift
  iOS/App/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/App/Assets.xcassets/Contents.json
  iOS/App/Base.lproj/LaunchScreen.storyboard
  iOS/App/Info.plist
  iOS/App/ViewController.swift
  iOS/AppTests/HMShadowViewTests.swift
  iOS/AppTests/Info.plist
  iOS/Example.xcodeproj/project.pbxproj
  iOS/Example/AppDelegate.swift
  iOS/Example/Base.lproj/Main.storyboard
  iOS/Hummer/Classes/Component/Views/View/UIView+HMAttribute.m
  iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.h
  iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
  iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
  iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
  iOS/Hummer/Classes/Core/Utility/HMConverter.h
  iOS/Hummer/Classes/Core/Utility/HMConverter.m
  iOS/Podfile
  iOS/Podfile.lock
Labels: enhancement

#267 fix(iOS): border box missing condition
  docs/yoga.md
  iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
Labels: bug

#281 fix(iOS): Define same class name as Hummer exported native class
  iOS/Hummer/Assets/Assets.xcassets/builtin.dataset/builtin.js
  iOS/builtin/src/HummerBase.ts
Labels: bug

#282 feat(iOS): Add HMSizeThatFitsMode change function
  iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.h
  iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.m
Labels: enhancement
