Repository didi/Hummer, pull requests merged in 2021-01, with the labels that each got.

#10 fix(iOS): hummerSetFrame modify bounds.origin bug
  iOS/Hummer/Classes/Component/Views/Scroller/HMScrollView.m
Labels: bug

#11 feat(iOS): Add ShadowView Unit Test
  iOS/Example.xcodeproj/project.pbxproj
  iOS/Example/AppDelegate.swift
  iOS/Example/Info.plist
  iOS/ExampleTests/ExampleTests.swift
  iOS/ExampleTests/HMShadowViewTests.swift
Labels: enhancement

#14 fix: Accessbility conflict with React Native
  iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
Labels: bug

#19 feat: Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CHANGELOG.md
Labels: enhancement

#21 fix: ISSUE_TEMPLATE.md YAML front matter error ad so on
  .github/ISSUE_TEMPLATE.md
  docs/CHANGELOG.md
Labels: bug

#23 fix: ISSUE_TEMPLATE.md error
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#22 fix: HMUIManager origin.y plus oldOrigin.x error
  iOS/Hummer/Classes/Core/Layout/Manager/HMUIManager.m
Labels: bug

#25 feat: Add config.yml
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug

#26 Update issue templates
  .github/ISSUE_TEMPLATE/---bug-report.md
Labels: enhancement

#27 chore: Move bug_report.md to ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug

#28 chore: Remove manual ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: bug

#29 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#30 Create config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#31 chore: Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#32 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#34 feat(iOS): Add Abstract JSContext, JSValue and ExceptionModel
  Hummer.podspec
  iOS/Hummer/Classes/Engine/HMBaseExecutor.h
  iOS/Hummer/Classes/Engine/HMBaseExecutor.m
  iOS/Hummer/Classes/Engine/HMBaseValue.h
  iOS/Hummer/Classes/Engine/HMBaseValue.m
  iOS/Hummer/Classes/Engine/HMBaseWeakValue.h
  iOS/Hummer/Classes/Engine/HMBaseWeakValue.m
  iOS/Hummer/Classes/Engine/HMExceptionModel.h
  iOS/Hummer/Classes/Engine/HMExceptionModel.m
Labels: enhancement

#35 Feature/issue 33
  iOS/Hummer/Classes/Engine/HMBaseExecutor.h
  iOS/Hummer/Classes/Engine/HMBaseExecutor.m
  iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
  iOS/Hummer/Classes/Engine/HMBaseValue.h
  iOS/Hummer/Classes/Engine/HMBaseValue.m
  iOS/Hummer/Classes/Engine/HMBaseWeakValue.m
  iOS/Hummer/Classes/Engine/HMBaseWeakValueProtocol.h
Labels: Platform: iOS, enhancement

#36 feat(iOS): Implement JavaScriptCore JSValue
  iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
  iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.m
  iOS/Hummer/Classes/Engine/HMBaseValue.h
  iOS/Hummer/Classes/Engine/HMBaseWeakValueProtocol.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor+Private.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue+Private.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCValue.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCWeakValue.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCWeakValue.m
Labels: Platform: iOS, enhancement

#43 feat(iOS): HMJSCExecutor enhancement
  Hummer.podspec
  iOS/Hummer/Assets/Assets.xcassets/builtin.dataset/Contents.json
  iOS/Hummer/Assets/Assets.xcassets/builtin.dataset/builtin.js
  iOS/Hummer/Classes/Component/Animation/CAAnimation+Exp.m
  iOS/Hummer/Classes/Component/Network/HMRequest.m
  iOS/Hummer/Classes/Component/Views/Button/HMButton.m
  iOS/Hummer/Classes/Component/Views/Scroller/HMScrollView.m
  iOS/Hummer/Classes/Component/Views/View/UIView+HMEvent.m
  iOS/Hummer/Classes/Core/Bridge/HMJSContext.m
  iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.h
  iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
  iOS/Hummer/Classes/Core/Bridge/JSValue+Hummer.h
  iOS/Hummer/Classes/Core/Utility/Category/NSString+Hummer.m
  iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
  iOS/Hummer/Classes/Engine/HMBaseValue.h
  iOS/Hummer/Classes/Engine/HMBaseValue.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
  iOS/Podfile
  iOS/builtin/src/index.ts
Labels: Platform: iOS, enhancement

#44 fix(iOS): HMCompatibleRenderObject affect UIScrollView and hm_sizeThatFits:
  iOS/Hummer/Classes/Core/Layout/RenderObject/HMCompatibleRenderObject.m
  iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
  iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.h
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
Labels: Platform: iOS, bug

#45 fix(iOS): JavaScriptCore finalize callback assert crash
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.m
Labels: Platform: iOS, bug

#47 fix(iOS): JavaScriptCore finalize callback crash
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCStrongValue.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCWeakValue.m
Labels: Platform: iOS, bug

#48 fix(iOS)：ViewPager setCurrentItem bug
  iOS/Hummer/Classes/Component/Views/ViewPager/HMViewPager.m
Labels: Platform: iOS, bug

#52 fix: console.log print twice
  iOS/Hummer/Classes/Component/HMConsole.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
Labels: Platform: iOS, bug

#56 feat(iOS): Add number string force convert
  iOS/Hummer/Classes/Engine/HMBaseExecutorProtocol.h
  iOS/Hummer/Classes/Engine/HMBaseValue.m
  iOS/Hummer/Classes/Engine/JavaScriptCore/HMJSCExecutor.m
Labels: Platform: iOS, enhancement

#57 fix(iOS): fixed bugs
  iOS/Hummer/Classes/Component/Animation/TransitionAnimation/HMTransitionAnimationConverter.m
  iOS/Hummer/Classes/Component/Views/View/UIView+HMAttribute.h
  iOS/Hummer/Classes/Component/Views/View/UIView+HMAttribute.m
  iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.h
  iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
  iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
Labels: Platform: iOS, bug

#61 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#62 chore(iOS): Remove comment
  iOS/Hummer/Classes/Component/Controller/HMViewController.m
Labels: bug

#63 refactor(iOS): HMNotification
  iOS/Hummer/Classes/Component/NotifyCenter/HMNotifyCenter.m
  iOS/Hummer/Classes/Component/Views/Scroller/HMScrollView.m
Labels: Platform: iOS, bug

#65 Feature/android update
  android/hummer-component/src/main/java/com/didi/hummer/component/viewpager/ViewPager.java
  android/hummer-core/src/debug/assets/HummerDefinition_es5.js
  android/hummer-core/src/debug/assets/babel.js
  android/hummer-core/src/main/java/com/didi/hummer/core/engine/jsc/JSCCallback.java
  android/hummer-core/src/main/jni/jsc/hummer/JSCCache.cpp
  android/hummer-core/src/main/jni/jsc/hummer/JSCCache.h
  android/hummer-core/src/main/jni/jsc/hummer/JavaScriptRuntime.cpp
  android/hummer-core/src/main/jni/jsc/hummer/TypeConvertor.cpp
  android/hummer-core/src/main/jni/jsc/hummer/TypeConvertor.h
  android/hummer-sdk/src/main/java/com/didi/hummer/context/HummerContext.java
  android/hummer-sdk/src/main/java/com/didi/hummer/hotload/HotLoader.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/style/HummerLayout.java
  android/hummer/src/main/java/com/didi/hummer/HummerDebugger.java
Labels: Platform: Android, bug

#66 feat(Android): android release version: 0.3.16
  android/gradle.properties
Labels: Platform: Android, enhancement
