Repository didi/Hummer, pull requests merged in 2021-02, with the labels that each got.

#68 fix(iOS): Inner code sync
  iOS/Hummer/Classes/Component/Controller/HMViewController.m
  iOS/Hummer/Classes/Component/NotifyCenter/HMNotifyCenter.m
  iOS/Hummer/Classes/Component/Views/View/UIView+HMDom.m
  iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
  iOS/Hummer/Classes/Core/Bridge/HMJSGlobal.m
  iOS/Hummer/Classes/Core/Utility/HMLayoutUtils.m
Labels: enhancement

#71 fix(Android): 日常bugfix
  android/gradle.properties
  android/hummer-component/src/main/java/com/didi/hummer/component/imageview/Image.java
  android/hummer-component/src/main/java/com/didi/hummer/component/imageview/ImageRenderUtil.java
  android/hummer-component/src/main/java/com/didi/hummer/component/scroller/Scroller.java
  android/hummer-sdk/build.gradle
  android/hummer-sdk/src/main/AndroidManifest.xml
  android/hummer-sdk/src/main/java/com/didi/hummer/HummerSDK.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/imageloader/IImageLoaderAdapter.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/imageloader/ImageSizeCallback.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/imageloader/impl/DefaultImageLoaderAdapter.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/location/impl/DefaultLocationAdapter.java
  android/hummer-sdk/src/main/java/com/didi/hummer/module/notifycenter/NotifyCenter.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/AssetsUtil.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/FileUtil.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/IntentUtils.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/LocationUtils.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/PermissionConstants.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/PermissionUtils.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/Utils.java
  android/hummer-sdk/src/main/java/com/didi/hummer/utils/blankj/UtilsTransActivity.java
  android/hummer-sdk/src/main/res/values-v21/values-v21.xml
  android/hummer-sdk/src/main/res/values/values.xml
Labels: Platform: Android, bug

#72 fix(iOS): Error
  iOS/ExampleTests/HMShadowViewTests.swift
  iOS/Hummer/Classes/Core/Bridge/HMJSContext.h
  iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
  iOS/Hummer/Classes/Core/Layout/RenderObject/HMYogaUtility.cpp
  iOS/Hummer/Classes/Core/Layout/RenderObject/HMYogaUtility.h
  iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.h
  iOS/Hummer/Classes/Core/Layout/UIView+HMRenderObject.m
Labels: bug

#73 fix(iOS): Build error
  iOS/Hummer/Classes/Core/Layout/RenderObject/HMRenderObject.m
Labels: bug

#78 fix(Android): 日常bugfix
  android/README.md
  android/ReleaseNotes.md
  android/config.gradle
  android/gradle.properties
  android/hummer-component/src/main/java/com/didi/hummer/component/list/List.java
  android/hummer-component/src/main/java/com/didi/hummer/component/viewpager/ViewPager.java
  android/hummer-core/src/debug/assets/HummerDefinition_es5.js
  android/hummer-core/src/debug/assets/babel.js
  android/hummer-core/src/main/assets/HummerDefinition.js
  android/hummer-core/src/main/assets/hummer_component.js
  android/hummer-core/src/main/assets/hummer_sdk.js
  android/hummer-core/src/main/jni/hermes/hummer/TypeConvertor.cpp
  android/hummer-dev-tools/src/main/java/com/didi/hummer/devtools/widget/ConsoleView.java
  android/hummer-sdk/src/main/java/com/didi/hummer/HummerConfig.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/HummerAdapter.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/scriptloader/IScriptLoaderAdapter.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/scriptloader/ScriptLoadCallback.java
  android/hummer-sdk/src/main/java/com/didi/hummer/adapter/scriptloader/impl/DefaultScriptLoaderAdapter.java
  android/hummer-sdk/src/main/java/com/didi/hummer/context/HummerInvoker.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/component/view/HMBase.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/component/view/HMGestureEventDetector.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/component/view/HummerLayoutExtendView.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/EventManager.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/base/Event.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/base/TraceEvent.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/guesture/LongPressEvent.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/guesture/PanEvent.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/guesture/PinchEvent.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/guesture/SwipeEvent.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/guesture/TapEvent.java
  android/hummer-sdk/src/main/java/com/didi/hummer/render/event/guesture/TouchEvent.java
  android/hummer-test/src/Comp_List.js
Labels: Platform: Android, bug, enhancement
